apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook-cfg
  labels:
    app: sidecar-injector
webhooks:
- name: sidecar-injector.morven.me
  clientConfig:
    service:
      name: sidecar-injector-webhook-svc
      namespace: sidecar-injector
      path: "/mutate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01USXdNekE0TlRnek5Gb1hEVE13TVRJd01UQTROVGd6TkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHBICkxDY3ZidVdSR2tWTzVjNXgzWE1icnp5Z0U2OG1RaWlSMFBNR1hsbXA5alEzQXVwUmQxK2twdlZsSUlXYUpIb2MKb3pFeFNuQnk2RmV6OGV2T0JnZ1ptZkxwdDU0WEhtOFhlaU1vc3hCMFFndWRCSGN6NGJYQkV4b2djWkhONGpkKwpsNk4yc2NoZmhFckdMdG1td3N0Ym1DRTJGRGxlS0ErODdZckRTZytjcXdHUTdJZjYvRzlrUjdud21lVmJyUWxTCitYZ3dEdTdYQkR1VTVGdHI4b2pFNlZkVllOcGxRa1ZUU1RJcDZNaEhQZlQ0RkdyK1NoWXJobC96V3ZHYW55VG8KWjRMQjYzdjIrdXY4VGpZc3hUZzJxbXhlSWhFbDhZSVNJb2RrR0l1WGtyaDlzRU5ONVNMdU9nVURQeUZ3MmEzOQpjMzBtb0U5NFdYSEg5VXZDc2RNQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIcExEaHlvNG9KdkxabFFXZTBtTGN4SnpFelQKT3YwcTNDVzBnNWc2cWF5WlZqc0JqTklRMW9rWE1jZEVQbFVWeWwwaUpVTnppZUtYZ2MwaHJPcGNLSjM1bWpsKwpwQkYxSS8vemRoeFlHUTJSV2szSUJ3VGFsZ3Y3L2tXQlVhcUhsWlU2c280bk02UThpenNBOXcyL0Erc1owYW95CkVQdVQzaDczQ3AzZG4yQlh4YkF5UHF5aTJ6R2RnVEp2L1FaN0FtSTVlRERpVDlBS2ZtQ0gxNE43NlpUMnhsWHIKNjNkS3owNUh1d1ZSMXh1YVJnZUpqa1VGVndmc1J0YWY2L2pLMktRZkJEeXZUNTNhYU1qMGg5RTZFb29SWWp4SgpBRVkycWtJVlByMkJBM3dBb2ZiUUR1Zi8xWm9LQ01lZ2s0a0pBQ3ZxRDR0SnV5cjB2NjVYZFhOeWs0UT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  namespaceSelector:
    matchLabels:
      sidecar-injection: enabled
